"""
Core data structures for game resources and population management.

This module provides the foundational data classes for managing:
- Expendable city resources (food, timber, wealth, metal)
- Expendable empire resources (efficiency, knowledge)
- Population tracking by age and employment status
- Societal resources combining population and morale
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass, field
from typing import Optional

from ..core.gameobject import GameObject, DataclassGameObject


class GameDataclass():
    """
    Base class for game data structures that support arithmetic operations.
    
    Allows numeric attributes to be combined with other instances or scalars
    using standard arithmetic operators. Non-numeric attributes are copied unchanged.
    """
    
    def copy(self):
        """Create a deep copy of this dataclass instance."""
        return deepcopy(self)
    
    def __operate(self, other, op):
        """Helper to perform numeric operation `op` on numeric attributes."""
        new_obj = self.__class__()
        
        for attr, value in self.__dict__.items():
            if isinstance(value, (int, float)):
                if isinstance(other, self.__class__):
                    other_value = getattr(other, attr, 0)
                    if isinstance(other_value, (int, float)):
                        setattr(new_obj, attr, op(value, other_value))
                    else:
                        setattr(new_obj, attr, value)
                elif isinstance(other, (int, float)):
                    setattr(new_obj, attr, op(value, other))
                else:
                    raise TypeError(
                        f"Unsupported operand type(s) for operation: "
                        f"'{type(self).__name__}' and '{type(other).__name__}'"
                    )
            else:
                setattr(new_obj, attr, value)
        return new_obj

    def __add__(self, other):
        return self.__operate(other, lambda a, b: a + b)

    def __sub__(self, other):
        return self.__operate(other, lambda a, b: a - b)

    def __mul__(self, other):
        return self.__operate(other, lambda a, b: a * b)

    def __truediv__(self, other):
        return self.__operate(other, lambda a, b: a / b if b != 0 else float('inf'))

    def __neg__(self):
        new_obj = self.__class__()
        for attr, value in self.__dict__.items():
            if isinstance(value, (int, float)):
                setattr(new_obj, attr, -value)
            else:
                setattr(new_obj, attr, value)
        return new_obj
    

@dataclass
class ExpendableCityResources(GameDataclass, DataclassGameObject):
    """
    Represents material resources available to a city.
    
    These resources are consumed or produced by buildings and can be
    transferred between cities. All values are floats to allow partial
    production/consumption during fractional ticks.
    
    Attributes:
        food: Used for population survival and unit creation
        timber: Used for building construction and unit creation
        wealth: Generated by markets and used for various purchases
        metal: Used for military units and advanced buildings
    """
    food: float = 0.0
    timber: float = 0.0
    wealth: float = 0.0
    metal: float = 0.0

    @classmethod
    def empty_resources(cls):
        """Create a resource object with all values set to zero."""
        return ExpendableCityResources(
            food=0,
            timber=0,
            wealth=0,
            metal=0
        )
    
    def __neg__(self) -> ExpendableCityResources:
        return ExpendableCityResources(
            food=-self.food,
            timber=-self.timber,
            wealth=-self.wealth,
            metal=-self.metal
        )


@dataclass
class Population(DataclassGameObject):
    """
    Simplified population tracking without age-based lists.
    
    Tracks total population, employable workers, and currently employed workers.
    Population growth and employment are managed as simple integer aggregates.
    
    Attributes:
        total_population: Total number of people in the city
        employable_population: Number of people trained to be workers
        employed_population: Number of employable people currently employed
    """
    total_population: int = 0
    employable_population: int = 0
    employed_population: int = 0
    
    def total(self) -> int:
        """Return total population."""
        return self.total_population
    
    def total_workers(self) -> int:
        """Return total trained workers."""
        return self.employable_population
    
    def employ_workers(self, num_workers: int) -> int:
        """
        Employ workers from the unemployed employable population.
        
        Args:
            num_workers: Number of workers to employ
            
        Returns:
            Number of workers actually employed (may be less if not enough available)
        """
        unemployed = self.employable_population - self.employed_population
        to_employ = min(unemployed, num_workers)
        if to_employ > 0:
            self.employed_population += to_employ
        return to_employ
    
    def layoff_workers(self, num_workers: int) -> int:
        """
        Lay off workers from the employed population.
        
        Args:
            num_workers: Number of workers to lay off
            
        Returns:
            Number of workers actually laid off (may be less if not enough employed)
        """
        to_layoff = min(self.employed_population, num_workers)
        if to_layoff > 0:
            self.employed_population -= to_layoff
        return to_layoff
    
    def add_population(self, num_people: int) -> None:
        """
        Add population to the city.
        
        Args:
            num_people: Number of people to add
        """
        self.total_population += num_people
        if self.total_population < 0:
            self.total_population = 0
    
    def remove_population(self, num_people: int) -> None:
        """
        Remove population from the city (deaths, emigration, etc).
        
        Args:
            num_people: Number of people to remove
        """
        self.total_population = max(0, self.total_population - num_people)
    
    def add_employable(self, num_workers: int) -> None:
        """
        Add trained workers to the employable population.
        
        Args:
            num_workers: Number of workers to train
        """
        self.employable_population += num_workers
    
    def remove_employable(self, num_workers: int) -> None:
        """
        Remove workers from the employable population.
        
        Args:
            num_workers: Number of workers to remove
        """
        self.employable_population = max(0, self.employable_population - num_workers)
        # Also reduce employed if needed
        if self.employed_population > self.employable_population:
            self.employed_population = self.employable_population


@dataclass
class SocietalResources(DataclassGameObject):
    """
    Aggregates population and morale metrics for a city.
    
    Attributes:
        population: Population data (total, employable, and employed)
        morale: City morale level (0-100, 50.0 is neutral)
    """
    population: Population = field(default_factory=Population)
    morale: float = 50.0  # currently unused (morale is its own category in the city). Delete?
    
    @property
    def employable_population(self) -> int:
        """Get total employable population."""
        return self.population.employable_population
    
    @property
    def employed_population(self) -> int:
        """Get total employed population."""
        return self.population.employed_population

# TODO: efficiency should be removed, as it's now handled as its own separate category
@dataclass
class ExpendableEmpireResources(GameDataclass, DataclassGameObject):
    """
    Represents non-material resources managed at the empire level.
    
    These resources affect all cities in an empire and represent
    empire-wide metrics rather than city-specific production.
    
    Attributes:
        efficiency: Government efficiency rating (0-100, higher = faster actions).
                   Related to corruption via: corruption = 100 - efficiency
        knowledge: Technical advancement (used to unlock buildings/units).
                  Floating point for precision when affected by percentage multipliers.
    """
    efficiency: float = 0.0  # Neutral efficiency (50% corruption)
    knowledge: float = 0.0


if __name__ == "__main__":
    original = ExpendableCityResources(
        food=45
    )
    increases = ExpendableCityResources(
        food=45
    )
    print(original + increases)