"""
Core data structures for game resources and population management.

This module provides the foundational data classes for managing:
- Expendable city resources (food, timber, wealth, metal)
- Expendable empire resources (efficiency, knowledge)
- Population tracking by age and employment status
- Societal resources combining population and morale
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass, field

from ..core.gameobject import GameObject


class GameDataclass(GameObject):
    """
    Base class for game data structures that support arithmetic operations.
    
    Allows numeric attributes to be combined with other instances or scalars
    using standard arithmetic operators. Non-numeric attributes are copied unchanged.
    """
    
    def copy(self):
        """Create a deep copy of this dataclass instance."""
        return deepcopy(self)
    
    def __operate(self, other, op):
        """Helper to perform numeric operation `op` on numeric attributes."""
        new_obj = self.__class__()
        
        for attr, value in self.__dict__.items():
            if isinstance(value, (int, float)):
                if isinstance(other, self.__class__):
                    other_value = getattr(other, attr, 0)
                    if isinstance(other_value, (int, float)):
                        setattr(new_obj, attr, op(value, other_value))
                    else:
                        setattr(new_obj, attr, value)
                elif isinstance(other, (int, float)):
                    setattr(new_obj, attr, op(value, other))
                else:
                    raise TypeError(
                        f"Unsupported operand type(s) for operation: "
                        f"'{type(self).__name__}' and '{type(other).__name__}'"
                    )
            else:
                setattr(new_obj, attr, value)
        return new_obj

    def __add__(self, other):
        return self.__operate(other, lambda a, b: a + b)

    def __sub__(self, other):
        return self.__operate(other, lambda a, b: a - b)

    def __mul__(self, other):
        return self.__operate(other, lambda a, b: a * b)

    def __truediv__(self, other):
        return self.__operate(other, lambda a, b: a / b if b != 0 else float('inf'))

    def __neg__(self):
        new_obj = self.__class__()
        for attr, value in self.__dict__.items():
            if isinstance(value, (int, float)):
                setattr(new_obj, attr, -value)
            else:
                setattr(new_obj, attr, value)
        return new_obj
    

@dataclass
class ExpendableCityResources(GameDataclass):
    """
    Represents material resources available to a city.
    
    These resources are consumed or produced by buildings and can be
    transferred between cities. All values are floats to allow partial
    production/consumption during fractional ticks.
    
    Attributes:
        food: Used for population survival and unit creation
        timber: Used for building construction and unit creation
        wealth: Generated by markets and used for various purchases
        metal: Used for military units and advanced buildings
    """
    food: float = 0.0
    timber: float = 0.0
    wealth: float = 0.0
    metal: float = 0.0

    @classmethod
    def empty_resources(cls):
        """Create a resource object with all values set to zero."""
        return ExpendableCityResources(
            food=0,
            timber=0,
            wealth=0,
            metal=0
        )
    
    def __neg__(self) -> ExpendableCityResources:
        return ExpendableCityResources(
            food=-self.food,
            timber=-self.timber,
            wealth=-self.wealth,
            metal=-self.metal
        )


@dataclass
class Population(GameObject):
    """
    Tracks city population by age group and employment capability.
    
    Population ages naturally each tick and dies based on lifespan.
    A subset of working-age population can be trained to become employable.
    
    Attributes:
        population_by_age: List where index n contains the count of people aged n years
        workers_by_age: List where index n contains trained workers aged n years
        max_lifespan: Maximum age a person can reach (deaths occur at this age)
    """
    population_by_age: list[int] = field(default_factory=lambda: [0]*100)
    workers_by_age: list[int] = field(default_factory=lambda: [0]*100)
    max_lifespan: int = 80  # Default lifespan (can be increased by hospitals)

    def add_population(self, num_people: int, age_group: int = 0) -> None:
        """
        Add population at a specific age group.
        
        Args:
            num_people: Number of people to add
            age_group: Age to add population at (default 0 for newborns)
        """
        if 0 <= age_group < len(self.population_by_age):
            self.population_by_age[age_group] += num_people
            
    def add_workers_by_age(self, num_workers: int, age_group: int) -> None:
        """
        Add trained workers at a specific age group.
        
        Args:
            num_workers: Number of workers to add
            age_group: Age of the workers
        """
        if 0 <= age_group < len(self.workers_by_age):
            self.workers_by_age[age_group] += num_workers

    def population_in_age_range(self, minimum: int, maximum: int) -> int:
        """
        Count total population in a given age range.
        
        Args:
            minimum: Minimum age (inclusive)
            maximum: Maximum age (inclusive)
            
        Returns:
            Total number of people in the specified age range
        """
        num = 0
        for age in range(minimum, maximum + 1):
            if age < len(self.population_by_age):
                num += self.population_by_age[age]
        return num
    
    def workers_in_age_range(self, minimum: int, maximum: int) -> int:
        """
        Count workers available in a given age range.
        
        Args:
            minimum: Minimum age (inclusive)
            maximum: Maximum age (inclusive)
            
        Returns:
            Number of available workers in the specified age range
        """
        num = 0
        for age in range(minimum, maximum + 1):
            if age < len(self.workers_by_age):
                num += self.workers_by_age[age]
        return num
    
    def total(self) -> int:
        """Return total population across all age groups."""
        return sum(self.population_by_age)
    
    def total_workers(self) -> int:
        """Return total trained workers across all age groups."""
        return sum(self.workers_by_age)
    
    def age_population(self) -> int:
        """
        Age the entire population by one year, handling deaths at max lifespan.
        
        Returns:
            Number of people who died from aging
        """
        deaths = 0
        # Age population backwards to avoid double-aging
        new_ages = [0] * len(self.population_by_age)
        new_workers = [0] * len(self.workers_by_age)
        
        for age in range(len(self.population_by_age)):
            if age < self.max_lifespan:
                # Move population to next age group
                new_ages[age + 1] = self.population_by_age[age]
                if age + 1 < len(self.workers_by_age):
                    new_workers[age + 1] = self.workers_by_age[age]
            else:
                # People at or beyond max lifespan die
                deaths += self.population_by_age[age]
        
        self.population_by_age = new_ages
        self.workers_by_age = new_workers
        return deaths


@dataclass
class SocietalResources(GameObject):
    """
    Aggregates population and morale metrics for a city.
    
    Attributes:
        population: Age-tracked population data
        employable_population: Workers trained to work (max = working age population)
        employed_population: Currently working population (max = employable_population)
        morale: City morale level (0-100, 50.0 is neutral)
    """
    population: Population = field(default_factory=Population)
    employable_population: int = 0
    employed_population: int = 0
    morale: float = 50.0 


@dataclass
class ExpendableEmpireResources(GameDataclass):
    """
    Represents non-material resources managed at the empire level.
    
    These resources affect all cities in an empire and represent
    empire-wide metrics rather than city-specific production.
    
    Attributes:
        efficiency: Government efficiency rating (0-100, higher = faster actions).
                   Related to corruption via: corruption = 100 - efficiency
        knowledge: Technical advancement (used to unlock buildings/units).
                  Floating point for precision when affected by percentage multipliers.
    """
    efficiency: float = 50.0  # Neutral efficiency (50% corruption)
    knowledge: float = 0.0


if __name__ == "__main__":
    original = ExpendableCityResources(
        food=45
    )
    increases = ExpendableCityResources(
        food=45
    )
    print(original + increases)