"""
Core data structures for game resources and population management.

This module provides the foundational data classes for managing:
- Expendable city resources (food, timber, wealth, metal)
- Expendable empire resources (efficiency, knowledge)
- Population tracking by age and employment status
- Societal resources combining population and morale
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass, field
from typing import Optional

from ..core.gameobject import GameObject, DataclassGameObject


class GameDataclass():
    """
    Base class for game data structures that support arithmetic operations.
    
    Allows numeric attributes to be combined with other instances or scalars
    using standard arithmetic operators. Non-numeric attributes are copied unchanged.
    """
    
    def copy(self):
        """Create a deep copy of this dataclass instance."""
        return deepcopy(self)
    
    def __operate(self, other, op):
        """Helper to perform numeric operation `op` on numeric attributes."""
        new_obj = self.__class__()
        
        for attr, value in self.__dict__.items():
            if isinstance(value, (int, float)):
                if isinstance(other, self.__class__):
                    other_value = getattr(other, attr, 0)
                    if isinstance(other_value, (int, float)):
                        setattr(new_obj, attr, op(value, other_value))
                    else:
                        setattr(new_obj, attr, value)
                elif isinstance(other, (int, float)):
                    setattr(new_obj, attr, op(value, other))
                else:
                    raise TypeError(
                        f"Unsupported operand type(s) for operation: "
                        f"'{type(self).__name__}' and '{type(other).__name__}'"
                    )
            else:
                setattr(new_obj, attr, value)
        return new_obj

    def __add__(self, other):
        return self.__operate(other, lambda a, b: a + b)

    def __sub__(self, other):
        return self.__operate(other, lambda a, b: a - b)

    def __mul__(self, other):
        return self.__operate(other, lambda a, b: a * b)

    def __truediv__(self, other):
        return self.__operate(other, lambda a, b: a / b if b != 0 else float('inf'))

    def __neg__(self):
        new_obj = self.__class__()
        for attr, value in self.__dict__.items():
            if isinstance(value, (int, float)):
                setattr(new_obj, attr, -value)
            else:
                setattr(new_obj, attr, value)
        return new_obj
    

@dataclass
class ExpendableCityResources(GameDataclass, DataclassGameObject):
    """
    Represents material resources available to a city.
    
    These resources are consumed or produced by buildings and can be
    transferred between cities. All values are floats to allow partial
    production/consumption during fractional ticks.
    
    Attributes:
        food: Used for population survival and unit creation
        timber: Used for building construction and unit creation
        wealth: Generated by markets and used for various purchases
        metal: Used for military units and advanced buildings
    """
    food: float = 0.0
    timber: float = 0.0
    wealth: float = 0.0
    metal: float = 0.0

    @classmethod
    def empty_resources(cls):
        """Create a resource object with all values set to zero."""
        return ExpendableCityResources(
            food=0,
            timber=0,
            wealth=0,
            metal=0
        )
    
    def __neg__(self) -> ExpendableCityResources:
        return ExpendableCityResources(
            food=-self.food,
            timber=-self.timber,
            wealth=-self.wealth,
            metal=-self.metal
        )


@dataclass
class Population(DataclassGameObject):
    """
    Tracks city population by age group and employment capability.
    
    Population ages naturally each tick and dies based on lifespan.
    A subset of working-age population can be trained to become employable.
    
    Attributes:
        population_by_age: List where index n contains the count of people aged n years
        employable_population_by_age: List where index n contains people who can work aged n years
        employed_population_by_age: List where index n contains people actively employed aged n years
        max_lifespan: Maximum age a person can reach (deaths occur at this age)
    """
    population_by_age: list[int] = field(default_factory=lambda: [0]*100)
    employable_population_by_age: list[int] = field(default_factory=lambda: [0]*100)
    employed_population_by_age: list[int] = field(default_factory=lambda: [0]*100)
    max_lifespan: int = 80  # Default lifespan (can be increased by hospitals)
    @property
    def unemployed_employable_population_by_age(self) -> list[int]:
        """Get list of employable but currently unemployed population by age."""
        unemployed = []
        for age in range(len(self.employable_population_by_age)):
            unemployed.append(
                self.employable_population_by_age[age] - self.employed_population_by_age[age]
            )
        return unemployed
    def add_population(self, num_people: int, age_group: int = 0) -> None:
        """
        Add population at a specific age group.
        
        Args:
            num_people: Number of people to add
            age_group: Age to add population at (default 0 for newborns)
        """
        if 0 <= age_group < len(self.population_by_age):
            self.population_by_age[age_group] += num_people
            
    def add_employable_by_age(self, age_group: int, num_workers: int) -> None:
        """
        Add trained workers at a specific age group.
        
        Args:
            age_group: Age of the workers
            num_workers: Number of workers to add
            
        """
        if 0 <= age_group < len(self.employable_population_by_age):
            self.employable_population_by_age[age_group] += num_workers
    def remove_employable_by_age(self, age_group: int, num_workers: Optional[int] = None) -> None:
        """
        Remove trained workers at a specific age group.
        
        Args:
            age_group: Age of the workers
            num_workers: Number of workers to remove. If None, then all workers are removed
            
        """
        if num_workers is None:
            self.employable_population_by_age[age_group] = 0
        else:
            self.employable_population_by_age[age_group] = max(0, self.employable_population_by_age[age_group] - num_workers)
    def population_in_age_range(self, minimum: int, maximum: int) -> int:
        """
        Count total population in a given age range.
        
        Args:
            minimum: Minimum age (inclusive)
            maximum: Maximum age (inclusive)
            
        Returns:
            Total number of people in the specified age range
        """
        num = 0
        for age in range(minimum, maximum + 1):
            if age < len(self.population_by_age):
                num += self.population_by_age[age]
        return num
    
    def workers_in_age_range(self, minimum: int, maximum: int) -> int:
        """
        Count workers available in a given age range.
        
        Args:
            minimum: Minimum age (inclusive)
            maximum: Maximum age (inclusive)
            
        Returns:
            Number of available workers in the specified age range
        """
        num = 0
        for age in range(minimum, maximum + 1):
            if age < len(self.employable_population_by_age):
                num += self.employable_population_by_age[age]
        return num
    
    def total(self) -> int:
        """Return total population across all age groups."""
        return sum(self.population_by_age)
    
    def total_workers(self) -> int:
        """Return total trained workers across all age groups."""
        return sum(self.employable_population_by_age)
    
    def employ_workers(self, num_workers: int) -> int:
        """
        Employ workers from the unemployed employable population.
        
        Takes from the pool of employable but unemployed workers across all age groups.
        
        Args:
            num_workers: Number of workers to employ
            
        Returns:
            Number of workers actually employed (may be less if not enough available)
        """
        employed = 0
        for age in range(len(self.employed_population_by_age)):
            unemployed = self.employable_population_by_age[age] - self.employed_population_by_age[age]
            to_employ = min(unemployed, num_workers - employed)
            if to_employ > 0:
                self.employed_population_by_age[age] += to_employ
                employed += to_employ
                if employed >= num_workers:
                    break
        return employed
    
    def layoff_workers(self, num_workers: int) -> int:
        """
        Lay off workers from the employed population.
        
        Releases workers from employment across all age groups.
        
        Args:
            num_workers: Number of workers to lay off
            
        Returns:
            Number of workers actually laid off (may be less if not enough employed)
        """
        laid_off = 0
        for age in range(len(self.employed_population_by_age)):
            employed = self.employed_population_by_age[age]
            to_layoff = min(employed, num_workers - laid_off)
            if to_layoff > 0:
                self.employed_population_by_age[age] -= to_layoff
                laid_off += to_layoff
                if laid_off >= num_workers:
                    break
        return laid_off
    
    def age_population(self) -> int:
        """
        Age the entire population by one year, handling deaths at max lifespan.
        
        Returns:
            Number of people who died from aging
        """
        deaths = 0
        # Age population backwards to avoid double-aging
        new_ages = [0] * len(self.population_by_age)
        new_workers = [0] * len(self.employable_population_by_age)
        new_employed = [0] * len(self.employed_population_by_age)
        
        for age in range(len(self.population_by_age)):
            if age < self.max_lifespan:
                # Move population to next age group
                new_ages[age + 1] = self.population_by_age[age]
                if age + 1 < len(self.employable_population_by_age):
                    new_workers[age + 1] = self.employable_population_by_age[age]
                if age + 1 < len(self.employed_population_by_age):
                    new_employed[age + 1] = self.employed_population_by_age[age]
            else:
                # People at or beyond max lifespan die
                deaths += self.population_by_age[age]
        
        self.population_by_age = new_ages
        self.employable_population_by_age = new_workers
        self.employed_population_by_age = new_employed
        return deaths


@dataclass
class SocietalResources(DataclassGameObject):
    """
    Aggregates population and morale metrics for a city.
    
    Attributes:
        population: Age-tracked population data with employable and employed breakdowns by age
        morale: City morale level (0-100, 50.0 is neutral)
    
    Note: employable_population and employed_population are computed from Population's
    employable_population_by_age and employed_population_by_age lists and should not be stored.
    """
    population: Population = field(default_factory=Population)
    morale: float = 50.0  # currently unused, might remove
    
    @property
    def employable_population(self) -> int:
        """Calculate total employable population across all age groups."""
        return sum(self.population.employable_population_by_age)
    
    @property
    def employed_population(self) -> int:
        """Calculate total employed population across all age groups."""
        return sum(self.population.employed_population_by_age)


@dataclass
class ExpendableEmpireResources(GameDataclass, DataclassGameObject):
    """
    Represents non-material resources managed at the empire level.
    
    These resources affect all cities in an empire and represent
    empire-wide metrics rather than city-specific production.
    
    Attributes:
        efficiency: Government efficiency rating (0-100, higher = faster actions).
                   Related to corruption via: corruption = 100 - efficiency
        knowledge: Technical advancement (used to unlock buildings/units).
                  Floating point for precision when affected by percentage multipliers.
    """
    efficiency: float = 50.0  # Neutral efficiency (50% corruption)
    knowledge: float = 0.0


if __name__ == "__main__":
    original = ExpendableCityResources(
        food=45
    )
    increases = ExpendableCityResources(
        food=45
    )
    print(original + increases)